version: "3.9"

services:
  apollo:
    image: apollo
    build:
      # context definuje cestu k popisu
      context: .
    environment:
      # promenne, ktere lze cist v kontejneru
      - PORT=3000
      # - |
      #   SERVICES=
      #   [
      #     {"name": "ug", "url": "http://gql_ug:8000/gql"}
      #   ]

    healthcheck:
      # definice, umoznujici provest test, zda je kontejner v poradku (vsimnete si portu a srovnejte s portem v environment)
      interval: 60s
      retries: 3
      start_period: 60s
      timeout: 10s
    restart: on-failure:3 # nedojde k restartu pokud je kontejner "unhealthy", maximalne 3 pokusy
    ports: #v deploymentu by nebylo zadne mapovani portu
    #   # vnejsi port : port, kde sluzbu poskytuje kontejner
      - 33000:3000

